// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiShowManagement.RazorWebApps.Models;

public partial class Animal
{
    public int AnimalId { get; set; }

    public string AnimalName { get; set; }

    public int? VarietyId { get; set; }

    public int? Size { get; set; }

    public DateTime? BirthDate { get; set; }

    public string Image { get; set; }

    public int? Weight { get; set; }

    public string AnimalDescription { get; set; }

    public string CountryOfOrigin { get; set; }

    public string HealthStatus { get; set; }

    public int? Gender { get; set; }

    public double? Rating { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual ICollection<Registration> Registrations { get; set; } = new List<Registration>();

    public virtual AnimalVariety Variety { get; set; }
}