// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiShowManagement.RazorWebApps.Models;

public partial class Competition
{
    public int CompetitionId { get; set; }

    public string CompetitionName { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string Location { get; set; }

    public int CompetitionTypeId { get; set; }

    public int? Status { get; set; }

    public int? NumberOfParticipants { get; set; }

    public string Image { get; set; }

    public string ContactInfo { get; set; }

    public int? ShapePointPercentage { get; set; }

    public int? ColorPointPercentage { get; set; }

    public int? PatternPointPercentage { get; set; }

    public string RulesDocument { get; set; }

    public string JudgingPanel { get; set; }

    public int? MaxJudges { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual ICollection<CompetitionCategory> CompetitionCategories { get; set; } = new List<CompetitionCategory>();

    public virtual CompetitionType CompetitionType { get; set; }

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual ICollection<FinalResult> FinalResults { get; set; } = new List<FinalResult>();

    public virtual ICollection<Registration> Registrations { get; set; } = new List<Registration>();
}