// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiShowManagement.RazorWebApps.Models;

public partial class CompetitionType
{
    public int CompetitionTypeId { get; set; }

    public string CompetitionTypeName { get; set; }

    public virtual ICollection<Competition> Competitions { get; set; } = new List<Competition>();
}