// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiShowManagement.RazorWebApps.Models;

public partial class Payment
{
    public int PaymentId { get; set; }

    public int? RegistrationId { get; set; }

    public string TransactionId { get; set; }

    public double? PaymentAmount { get; set; }

    public DateTime? PaymentDate { get; set; }

    public string PaymentStatus { get; set; }

    public string Description { get; set; }

    public double? Vatrate { get; set; }

    public double? ActualCost { get; set; }

    public double? DiscountAmount { get; set; }

    public double? FinalAmount { get; set; }

    public string Currency { get; set; }

    public string PaymentMethod { get; set; }

    public virtual Registration Registration { get; set; }
}