// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiShowManagement.RazorWebApps.Models;

public partial class PointOnProgressing
{
    public int PointId { get; set; }

    public int? ShapePoint { get; set; }

    public int? ColorPoint { get; set; }

    public int? PatternPoint { get; set; }

    public string Comment { get; set; }

    public int? JuryId { get; set; }

    public int? RegistrationId { get; set; }

    public int? PointStatus { get; set; }

    public string JudgeRank { get; set; }

    public int? PenaltyPoints { get; set; }

    public int? TotalScore { get; set; }

    public bool? IsDeleted { get; set; }

    public int? CategoryId { get; set; }

    public virtual CompetitionCategory Category { get; set; }

    public virtual User Jury { get; set; }

    public virtual Registration Registration { get; set; }
}