// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiShowManagement.Repositories.Models;

public partial class CompetitionCategory
{
    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public int CompetitionId { get; set; }

    public int? VarietyId { get; set; }

    public int? MinSize { get; set; }

    public int? MaxSize { get; set; }

    public int? MinAge { get; set; }

    public int? MaxAge { get; set; }

    public string JudgingCriteria { get; set; }

    public int? WeightPercentageForShape { get; set; }

    public int? WeightPercentageForColor { get; set; }

    public int? WeightPercentageForPattern { get; set; }

    public string RequiredHealthStatus { get; set; }

    public string RequiredDocuments { get; set; }

    public double? CompetitionFee { get; set; }

    public int? MaxParticipants { get; set; }

    public string PrizeDescription { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual Competition Competition { get; set; }

    public virtual ICollection<FinalResult> FinalResults { get; set; } = new List<FinalResult>();

    public virtual ICollection<PointOnProgressing> PointOnProgressings { get; set; } = new List<PointOnProgressing>();

    public virtual AnimalVariety Variety { get; set; }
}